export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';
export const CLEAR_CART_PRODUCTS = 'CLEAR_CART_PRODUCTS';
export const INC_CART_PRODUCT = 'INC_CART_PRODUCT';
export const DEC_CART_PRODUCT = 'DEC_CART_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
